### ISSUE TITLE
코드 사용문의

### ISSUE THREAD

**Issue by DevBeomsang** [netscout/chocopy#1]
안녕하세요 먼저 허락을 받았어야 했는데 나름대로 깃 연습하다가 연락을 먼저 못드렸네요 죄송합니다.
초코파이 시즌2 주간리포트 자동화코드를 다운받아서 나름대로 연습한 다음에 제 레포에 올렸습니다. 혹시 그래도 될까요? 문제시 바로 삭제하겠습니다

감사합니다

**Comment by netscout** [comment]
안녕하세요.

자유롭게 이용하셔도 괜찮습니다.

더 좋은 코드로 개량하셔서 다른 분들께 도움되도록 공유 부탁드립니다.

감사합니다.
